apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
spec:
  storageClassName: csi-rbd-3-sc # Or remove this line to use the default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi